### ISSUE TITLE
test analyzer : parser for test expressions duplicated

### ISSUE THREAD

**Issue by treinen** [colis-anr/shstats#17]
the ad-hoc parser for test expressions is now in morsmall. However, the test analyzer has a copy of the code since morsmall does not export the parsing function for test expressions. What is the best way to solve this ? Have morsmall export the parsing function ?

**Comment by Niols** [comment]
It is exported! Everything is accessible, although not necessarily in the lib's main module. This parser can be found in [Morsmall.Utilities.TestParser](https://colis-anr.github.io/docs/morsmall.0.2.0/Morsmall_utilities/TestParser/index.html). Is that alright or should we move this?

**Comment by treinen** [comment]
Yes thanks, that's fine.
